---
title: "DNA Block"
subtitle: "Preparation for DNA-related analyses"
---

## Papers we will discuss in class

Schep AN, Buenrostro JD, Denny SK, Schwartz K, Sherlock G, Greenleaf WJ. Structured nucleosome fingerprints enable high-resolution mapping of chromatin architecture within regulatory regions. Genome Res. 2015 PMID: 26314830; PMCID: PMC4617971 [\[Link\]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4617971/)

Zentner GE, Henikoff S. Mot1 redistributes TBP from TATA-containing to TATA-less promoters. Mol Cell Biol. 2013 PMID: 24144978; PMCID: PMC3889552. [\[Link\]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3889552/)

## Other work

This study was the first to analyze chromatin accessibility by high throughput DNA sequencing.

Hesselberth JR, Chen X, Zhang Z, Sabo PJ, Sandstrom R, Reynolds AP, Thurman RE, Neph S, Kuehn MS, Noble WS, Fields S, Stamatoyannopoulos JA. Global mapping of protein-DNA interactions in vivo by digital genomic footprinting. Nat Methods. 2009 19305407; PMCID: PMC2668528. [\[Link\]](https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/19305407/)

This study used MNase profiling to show that nucleosomal disassembly intermediates report on transcriptional state.

Ramachandran S, Ahmad K, Henikoff S. Transcription and Remodeling Produce Asymmetrically Unwrapped Nucleosomal Intermediates. Mol Cell. 2017 PMID: 29225036; PMCID: PMC6421108. [\[Link\]](https://linkinghub.elsevier.com/retrieve/pii/S1097-2765(17)30874-2)

This study describes the development of CUT&RUN.

Skene PJ, Henikoff S. An efficient targeted nuclease strategy for high-resolution mapping of DNA binding sites. Elife. 2017 PMID: 28079019; PMCID: PMC5310842. [\[Link\]](https://pubmed.ncbi.nlm.nih.gov/28079019/)
