---
title: "Preparation for long-read squencing"
author: "JH"
---

These recent papers provide insights that could only be made with the information gleaned by long-read sequencing.

### Long-read RNA sequencing

Alfonso-Gonzalez C, Legnini I, Holec S, Arrigoni L, Ozbulut HC, Mateos F, Koppstein D, Rybak-Wolf A, Bönisch U, Rajewsky N, Hilgers V. **Sites of transcription initiation drive mRNA isoform selection.** Cell. 2023 PMID: 37178687; PMCID: PMC10228280. [[Link]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10228280/)

Choquet K, Baxter-Koenigs AR, Dülk SL, Smalec BM, Rouskin S, Churchman LS. **Pre-mRNA splicing order is predetermined and maintains splicing fidelity across multi-intronic transcripts.** Nat Struct Mol Biol. 2023 Aug;30(8):1064-1076. doi: 10.1038/s41594-023-01035-2. Epub 2023 Jul 13. PMID: 37443198.

### Long-read DNA sequencing

Nurk S, Koren S, Rhie A, Rautiainen M, Bzikadze AV, Mikheenko A, Vollger MR, Altemose N, Uralsky L, Gershman A, Aganezov S, Hoyt SJ, Diekhans M, Logsdon GA, Alonge M, Antonarakis SE, Borchers M, Bouffard GG, Brooks SY, Caldas GV, Chen NC, Cheng H, Chin CS, Chow W, de Lima LG, Dishuck PC, Durbin R, Dvorkina T, Fiddes IT, Formenti G, Fulton RS, Fungtammasan A, Garrison E, Grady PGS, Graves-Lindsay TA, Hall IM, Hansen NF, Hartley GA, Haukness M, Howe K, Hunkapiller MW, Jain C, Jain M, Jarvis ED, Kerpedjiev P, Kirsche M, Kolmogorov M, Korlach J, Kremitzki M, Li H, Maduro VV, Marschall T, McCartney AM, McDaniel J, Miller DE, Mullikin JC, Myers EW, Olson ND, Paten B, Peluso P, Pevzner PA, Porubsky D, Potapova T, Rogaev EI, Rosenfeld JA, Salzberg SL, Schneider VA, Sedlazeck FJ, Shafin K, Shew CJ, Shumate A, Sims Y, Smit AFA, Soto DC, Sović I, Storer JM, Streets A, Sullivan BA, Thibaud-Nissen F, Torrance J, Wagner J, Walenz BP, Wenger A, Wood JMD, Xiao C, Yan SM, Young AC, Zarate S, Surti U, McCoy RC, Dennis MY, Alexandrov IA, Gerton JL, O'Neill RJ, Timp W, Zook JM, Schatz MC, Eichler EE, Miga KH, Phillippy AM. **The complete sequence of a human genome.** Science. 2022  PMID: 35357919; PMCID: PMC9186530. [[Link]](https://pubmed.ncbi.nlm.nih.gov/35357919/)

Stergachis AB, Debo BM, Haugen E, Churchman LS, Stamatoyannopoulos JA. **Single-molecule regulatory architectures captured by chromatin fiber sequencing.** Science. 2020 Jun 26;368(6498):1449-1454. doi: 10.1126/science.aaz1646. PMID: 32587015.