---
title: "Analysis tools for chromatin accessbility"
author: "JH"
---

## Tools we'll use in class

- Read over the [GViz vignette](https://bioconductor.org/packages/devel/bioc/vignettes/Gviz/inst/doc/Gviz.html) to understand how we'll use it to vissualize genome-scale data on a reference sequence.

- Read over the [valr vignette](https://rnabioco.github.io/valr/articles/valr.html) to understand how we'll do BEDtools-like (see below) analysis within RStudio.

- Look over the [ComplexHeatmap]() and [EnrichedHeatmap]() documentation, especially XXX. These tools will help us make "meta-plots": figures that plot genomic signals relative to features.

## Other important tools

- [BEDtools](https://bedtools.readthedocs.io/en/latest/) is the "Swiss Army knife" of genome interval analysis. It provides a host of command-line tools that can be linked together for powerful genome signal manipulation.

### Alignment software

[Bowtie2]() and [BWA]() are popular choices for short read alignment. They are fast, free, and well-maintained. 

### Peak calling

[MACS](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2592715/) is the gold-standard in peak calling. It models read coverage as a Poisson process, straightforward identification of regions of higher than expected coverage (i.e., peaks) to be identified using a single parmaeter (lambda) that captures the mean and variance of read coverage.

### Genome visualization

