---
title: "MOLB 7950: Informatics for Molecular Biology"
---

lessons:

  - title: "**Week 01: Bootcamp**"
  - date: "Mon, Aug 29"
    title: "Course overview / RStudio Cloud"
    instructor: "Hesselberth"
  - date: "Tues, Aug 30"
    title: "Bootcamp: Shell"
    instructor: "Hesselberth"
  - date: "Wed, Aug 31"
    title: "Bootcamp: Command line tools"
    instructor: "Hesselberth"
  - date: "Thurs, Sept 1"
    title: "Bootcamp: Command line tools"
    instructor: "Hesselberth"
  - date: "Fri, Sept 2"
    title: "Bootcamp: Python"
    instructor: "Ramachandran"

  - title: "**Week 02: Bootcamp**"
  - date: "Mon, Sept 5"
    title: "**No Class: Labor Day**"
  - date: "Tues, Sept 6"
    title: "Bootcamp: Python"
    instructor: "Taliaferro"
  - date: "Wed, Sept 7"
    title: "Bootcamp: Python"
    instructor: "Taliaferro"
  - date: "Thurs, Sept 8"
    title: "Bootcamp: Python"
    instructor: "Taliaferro"
  - date: "Fri, Sept 9"
    title: "Bootcamp: Python"
    instructor: "Taliaferro"

  - title: "**Week 03: Bootcamp**"
  - date: "Mon, Sept 12"
    title: "Bootcamp: R"
    instructor: "Hesselberth"
  - date: "Tues, Sept 13"
    title: "Bootcamp: R"
    instructor: "Hesselberth"
  - date: "Wed, Sept 14"
    title: "Bootcamp: R"
    instructor: "Hesselberth"
  - date: "Thurs, Sept 15"
    title: "Bootcamp: R"
    instructor: "Hesselberth"
  - date: "Fri, Sept 16"
    title: "Bootcamp: R"
    instructor: "Hesselberth"

  - title: "**Week 04: Bootcamp**"
  - date: "Mon, Sept 19"
    title: "Bootcamp: Statistical Concepts"
    instructor: "Ramachandran"
  - date: "Tues, Sept 20"
    title: "Bootcamp: Statistical Concepts"
    instructor: "Ramachandran"
  - date: "Wed, Sept 21"
    title: "Bootcamp: Statistical Concepts"
    instructor: "Mukherjee"
  - date: "Thus, Sept 22"
    title: "Bootcamp: Statistical Concepts"
    instructor: "Mukherjee"
  - date: "Fri, Sept 23"
    title: "Bootcamp: Statistical Concepts"
    instructor: "Mukherjee"

  - title: "**Week 05: DNA Block**"
  - date: "Mon, Sept 26"
    title: "ChIP-seq"
    instructor: "Ramachandran"
  - date: "Wed, Sept 28"
    title: "ChIP-seq"
    instructor: "Ramachandran"
  - date: "Fri, Sept 30"
    title: "Genome Sequencing: Short read"
    instructor: "Hesselberth"

  - title: "**Week 06: DNA Block**"
  - date: "Mon, Oct 3"
    title: "Genome Sequencing: Long read"
    instructor: "Hesselberth"
  - date: "Wed, Oct 5"
    title: "Chromatin accessibility"
    instructor: "Ramachandran"
  - date: "Fri, Oct 7"
    title: "Chromatin accessibility (CSDV retreat)"
    instructor: "Ramachandran"

  - title: "**Week 07: DNA Block**"
  - date: "Mon, Oct 10"
    title: "DNA Block Review"
    instructor: "Hesselberth/Ramachandran"
  - date: "Wed, Oct 12"
    title: "RNA-seq Basics"
    instructor: "Mukherjee"
  - date: "Fri, Oct 14"
    title: "Differential Gene Expression"
    instructor: "Taliaferro"
    slides: "rna-block/RNAseq_QC_slides.html"

  - title: "**Week 08: RNA Block**"
  - date: "Mon, Oct 17"
    title: "Differential Gene Expression"
    slides: "rna-block/RNAseq_DE_slides.html"
    instructor: "Taliaferro"
  - date: "Wed, Oct 19"
    title: "Alternative Splicing"
    slides: "rna-block/AS_slides_2022.html"
    instructor: "Taliaferro"
  - date: "Fri, Oct 21"
    title: "**No Class — MOLB RETREAT**"

  - title: "**Week 09: RNA Block**"
  - date: "Mon, Oct 24"
    title: "RNA binding protein-RNA interactions"
    instructor: "Mukherjee"
  - date: "Wed, Oct 26"
    title: "RNA binding protein-RNA interactions"
    instructor: "Mukherjee"
  - date: "Fri, Oct 28"
    title: "Single-cell mRNA sequencing"
    instructor: "Riemondy"

  - title: "**Week 10: RNA Block**"
  - date: "Mon, Oct 31"
    title: "Single-cell mRNA sequencing"
    instructor: "Riemondy"
  - date: "Wed, Nov 2"
    title: "Tutorial: Recreating analysis of published RNA-seq data sets"
    instructor: "Riemondy"
  - date: "Fri, Nov 4"
    title: "Block RNA Review — Discuss Final Projects"
    instructor: "Mukherjee/Taliaferro/Riemondy"

  - title: "**Week 11: Protein Block**"
  - date: "Mon, Nov 7"
    title: "Protein identification and sequence databases"
    instructor: "Hesselberth"
  - date: "Wed, Nov 9"
    title: "Quantitative mass spectrometry and analysis"
    instructor: "Hesselberth"
  - date: "Fri, Nov 11"
    title: "Protein Sequence and Domain Analysis"
    instructor: "Hesselberth"

  - title: "**Week 12: Protein Block**"
  - date: "Mon, Nov 14"
    title: "Multiple Sequence Alignments"
    instructor: "Hesselberth"
  - date: "Wed, Nov 16"
    title: "Tutorial: Visualizing and manipulating three-dimensional structures"
    instructor: "Lo"
  - date: "Fri, Nov 18"
    title: "Block Protein Review"
    instructor: "Hesselberth/Lo"

  - title: "**Week 13: Holiday week**"
  - date: "Mon, Nov 21"
    title: "**No Class — Holiday**"
  - date: "Wed, Nov 23"
    title: "**No Class — Holiday**"
  - date: "Fri, Nov 25"
    title: "**No Class — Holiday**"

  - title: "**Week 14: Final projects**"
  - date: "Mon, Nov 28"
    title: "Student Presentations"
  - date: "Wed, Nov 30"
    title: "Student Presentations"
  - date: "Fri, Dec 2"
    title: "Student Presentations"
