---
title: "Bootcamp resources"
author: "Jay Hesselberth"
date: last-modified
---

## R & RStudio

### Installation

- [Installing R](https://cran.r-project.org/)
- [Installing RStudio](https://posit.co/download/rstudio-desktop/)

### Books

- [Advanced R](https://adv-r.hadley.nz/)
- [Computational Genomics with R](https://compgenomr.github.io/book/)
- [R for Data Science (R4DS)](https://r4ds.hadley.nz/)
- [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/)

Quick reference:

- [Data tidying](https://r4ds.hadley.nz/data-tidy)
- [Your labels are too small.](https://clauswilke.com/dataviz/small-axis-labels.html). Use [cowplot themes](https://wilkelab.org/cowplot/reference/index.html#section-themes) to automatically adjust.

### R libraries

- The [Tidyverse](https://tidyverse.org) is a collection of libaries implementing a principled approach to data analysis.
- [Bioconductor](https://bioconductor.org) is a collection of libraries focused on biological data analysis.

### Cheat sheets

The tidyverse [cheat sheets](https://rstudio.github.io/cheatsheets/) are indispensible references.

Quick reference:

- [RStudio](https://rstudio.github.io/cheatsheets/html/rstudio-ide.html)
- [Rmarkdown](https://rstudio.github.io/cheatsheets/html/rmarkdown.html)
- [tidyr](https://rstudio.github.io/cheatsheets/html/tidyr.html)
- [dplyr](https://rstudio.github.io/cheatsheets/html/data-transformation.html)
- [ggplot2](https://rstudio.github.io/cheatsheets/html/data-visualization.html)

## Statistics

- [Practical Statistics for Data Scientists](https://github.com/gedeck/practical-statistics-for-data-scientists) covers several fundamental concepts with code for both R and Python.
- [Modern Statistics for Modern
  Biology](http://web.stanford.edu/class/bios221/book/) is written by two leading figures in computational biology and contains several examples using Bioconductor.
- [Statistics for
  Biologists](https://www.nature.com/collections/qghhqm) is a collection of articles on statistical topic. 

## Miscellaneous

- [Organizing projects](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424)
- [Happy Git with R](https://happygitwithr.com/)
