#### Problem Set Rubric

Problem sets are worth 60% of your grade. Values in parentheses represent point values for each level from 20 points total. This rubric will be assessed at the end of the semester.

| Criteria                                                                             | Expert                                                                                                                                                                                                                                     | Competent                                                                                                                                                            | Needs Improvement                                                                                                                        |
|------------------|------------------|--------------------|------------------|
| Coding style                                                                         | Student has gone beyond what was expected and required, coding manual is followed, code is well commented                                                                                                                                  | Coding style lacks refinement and has some errors, but code is readable and has some comments                                                                        | Many errors in coding style, little attention paid to making the code human readable                                                     |
| Coding strategy                                                                      | Complicated problem broken down into sub-problems that are individually much simpler. Code is efficient, correct, and minimal. Code uses appropriate data structure (list, data frame, vector/matrix/array). Code checks for common errors | Code is correct, but could be edited down to leaner code. Some "hacking" instead of using suitable data structure. Some checks for errors.                           | Code tackles complicated problem in one big chunk. Code is repetitive and could easily be functionalized. No anticipation of errors.     |
| Presentation: graphs                                                                 | Graph(s) carefully tuned for desired purpose. One graph illustrates one point                                                                                                                                                              | Graph(s) well chosen, but with a few minor problems: inappropriate aspect ratios, poor labels.                                                                       | Graph(s) poorly chosen to support questions.                                                                                             |
| Presentation: tables                                                                 | Table(s) carefully constructed to make it easy to perform important comparisons. Careful styling highlights important features.                                                                                                            | Table(s) generally appropriate but possibly some minor formatting deficiencies.                                                                                      | Table(s) with too many, or inconsistent, decimal places. Table(s) not appropriate for questions and findings. Major display problems.    |
| Achievement, mastery, cleverness, creativity                                         | Student has gone beyond what was expected and required, e.g., extraordinary effort, additional tools not addressed by this course, unusually sophisticated application of tools from course.                                               | Tools and techniques from the course are applied very competently and, perhaps,somewhat creatively. Chosen task was acceptable, but fairly conservative in ambition. | Student does not display the expected level of mastery of the tools and techniques in this course. Chosen task was too limited in scope. |
| Ease of access for instructor, compliance with course conventions for submitted work | Access as easy as possible, code runs!                                                                                                                                                                                                     | Satisfactory                                                                                                                                                         | Not an earnest effort to reduce friction and comply with conventions and/or code does not run                                            |

#### Participation rubric

Participation is worth 20% of your grade. Values in parentheses represent point values for each level from 20 points total. This rubric will be assessed at the end of the semester.

| Criteria                                                                                             | Expert                                            | Competent                                                                                      | Needs improvement                                                                              |
|------------------|------------------|--------------------|------------------|
| Attendance (physically present for class, or coordinating with instructor when absent)               | Attends class regularly (5)                       | Attends most classes (4)                                                                       | Attends some classes (0-3)                                                                     |
| Preparation (activities required for in-class participation, like surveys and software installation) | Completes requested activities prior to class (5) | Completes most requested activities prior to class, sometimes needs to finish during class (4) | Rarely completes requested activities prior to class, often takes class time to complete (0-3) |
| Engagement (in-class activities like coding exercises and discussion)                                | Actively engages in class activities (10)         | Sometimes engages in class activities (8)                                                      | Doesn't engage in class activities (0-7)                                                       |


