---
title: "MOLB 7950 — Course links"
---

In previous iterations of this course, we taught command-line (bash,
grep, awk, etc) and Python programming. These skills are 
useful, but for consistency we opted to focus on R programming and
RStudio as an analysis environment.

AMC also offers [shorter workshops](https://medschool.cuanschutz.edu/rbi/training-and-education/graduate-courses) on specific analysis strategies that
you might find helpful.

- [BMSC 7810: Practical biological data analysis with R/RStudio](https://rnabioco.github.io/bmsc-7810-pbda/) (RBI fellows)
- MOLB 7900: Practical Computational Biology for Biologists — Python (Taliaferro and Ramachandran)
- MOLB 7910: Practical Computational Biology for Biologists — R/R Studio (Jagannathan and Mukherjee)

## Recommended reading

We borrow from the following books and recommend referring them after the class
has completed. Many of them contain exercises for learning specific approaches (e.g., RNA-seq). 

### Data processing and visualization

- [R for Data Science](https://r4ds.had.co.nz/)
- [R Packages](https://r-pkgs.org/) is a thorough treatment of developing your own R packages.
- [Fundamentals of Data
  Visualization](https://serialmentor.com/dataviz/) contains several nice graphical display concepts, with 
  examples of what and what not to do in displaying data visually.

### Statistics

- [Practical Statistics for Data Scientists](https://github.com/gedeck/practical-statistics-for-data-scientists) covers several fundamental concepts with code for both R and Python.
- [Modern Statistics for Modern
  Biology](http://web.stanford.edu/class/bios221/book/) is written by two leading figures in computational biology and contains several examples using Bioconductor.
- [Statistics for
  Biologists](https://www.nature.com/collections/qghhqm) is a collection of articles on statistical topic. 

## Acknowldgements & Attribution

We have borrowed from several (open licensed) resources for course content, including:

- [Stats 545 at UBC](https://stat545.com/), particularly their grading rubrics
- [Courses from Mine Çetinkaya-Rundel](https://mine-cr.com/teaching/), mostly inspiration for quarto formats