---
title: "R Bootcamp - Day 3 - Exercises"
author: "Jay Hesselberth"
date: last-modified
---

```{r}
#| include: false
library(tidyverse)
library(knitr)
library(here)
```

## Today's datasets - Exercise 1

Explore these data sets:

* `dplyr::starwars`
* `dplyr::band_members`, `dplyr::band_instruments`, `dplyr::band_instruments2`

```{r}
```

## arrange - Exercise 2

```{r}
```

## filter - Exercise 3

```{r}
```

### filter by membership

```{r}
# filter based on skin color
```

Conditions can be combined using `&` (and), `|` (or).

```{r}
# filter on skin and eye color
```

### select - Exercise 4

```{r}
```

### mutate (& pipe |>)- Exercise 5

```{r}
# create a new column to display height in meters

# using the pipe to feed data into multiple functions sequentially

# mutate allows you to refer to columns that you’ve just created

# output needs to be saved into a new dataframe since dplyr does not "change" the original dataframe

# using if_else clauses with mutate
```

## case_when - Exercise 6

```{r}
# create categories based on height
```

```{r}
# multiple conditions with case_when
```

### summarise - Exercise 7

```{r}
```

### group_by + summarize - Exercise 8

```{r}
```

```{r}
# multiple grouping variables
```

## across - Exercise 9

```{r}
# apply mean to multiple columns
```

```{r}
# apply multiple functions with list()
```

```{r}
# combine across() with group_by()
```
