---
title: "MOLB 7950 -- Final Projects"
editor: 
  markdown: 
    wrap: 72
---

## Short proposal

Please submit a short proposal for your final projects with the
following information.

-   the names of people you are working with

-   a description of the data set you will be working worth. This can
    refer to a publication and/or contain a link to public data
    available at NCBI GEO.

-   a hypothesis (tentative) you will be testing

-   a few bullets on your planned analysis approach.

Please include this information in a quarto document in a new Posit
cloud project.

## Overview

-   Final projects can involve groups of 1-3 people.

-   Projects are choose your own adventure:

    1.  The [resource documents](resources/block-dna-resources.qmd)
        contain data sets in from human S. cerevisiae. For example,
        sub-nucleosomal fragments provide a DNA-based signal to
        understand chromatin transactions that lead to transcription.

    2.  You could find a data set on [NCBI
        GEO](https://www.ncbi.nlm.nih.gov/geo/) of interest (e.g.,
        relevant to your thesis work), and work it up with salmon,
        DEseq, and exploratory analysis. We are happy to help you work
        through the pseudo-alignment steps.

    3.  You can start with your own sequencing data (bulk/single-cell
        RNA seq, DNA sequencing).

## Deliverables

-   A Quarto document with code, plots, interpretations, and next steps.

-   If you work in a group, list the members of the group at the top of
    the document, and make it clear which parts are your work by adding
    your initials to code chunks.

-   Short presentations (5-8 minutes) by the groups the week of Nov 1.
    Presentations should include 1-2 slides of background, a hypothesis
    for the approach, code output (table or graph) that addresses the
    hypothesis, and one or more tests of the statistical significance of
    the observation.

## Grading and rubric

The final project will be worth 20% of your grade and we will use the
grading scheme outlined in the [grading
rubric](syllabus.qmd#problem-set-rubric).

Each individual in a group will be evaluated separately, so
contributions must be clearly marked in the document, using e.g. using
chunk labels:

```{r}
#| label: plotting-code-by-jay-h
#| eval: false
#| echo: fenced
ggplot(mtcars, aes(hp, mpg)) + geom_point()
```
