---
title: "MOLB 7950 — Problem Sets"
---

## Problem Set Overview

### Problem sets

We reinforce concepts with problem sets assigned at the end of each
class. During the main blocks, problem sets on Mon and Wed should take
\~60 minutes to complete. Problems sets assigned on Friday will be more
substantial, requiring \~1-2 hours to complete. Together the problem
sets constitute 60% of your grade.

### Submission

Problem sets are distributed as Posit Cloud assignments. You will work
on problem sets in an Rmarkdown document in the assignment. When complete,
complete your assignment by submitting the URL from your Posit Cloud assignment into the 
assignment submission on Canvas. We will grade your problem directly in the 
Posit Cloud assignment.

{{< include ../includes/_problem-set-due-dates.qmd >}}

### Problem Set Grading Rubric

Problem sets are worth 60% of your grade. Values in parentheses
represent point values for each level from 20 points total. This rubric
will be assessed at the end of the semester.

{{< include ../includes/_rubric-problem-sets.qmd >}}
