---
title: "Welcome e-mail"
format: html
---

Dear all,

I am writing to update you on preparations for MOLB 7950 (Informatics and Statistics for Molecular Biology) this Fall semester.

The course has a website (https://rnabioco.github.io/molb-7950) and the syllabus has dates for class, which starts Aug 28 at 9am. Class will be held in the new AHSB building room 2201.

The course begins with a bootcamp. For the first few weeks, we'll meet every morning from 9-10:30am to go over the tools we'll use in the course (R & Posit Cloud). We'll also discuss statistical considerations for the experiments that we'll cover in the main blocks.

After the bootcamp, the course has 2 blocks (DNA & RNA) that meet Mon-Wed-Fri 9-10:30 and cover analysis of specific types of experiments. We'll begin each class with a short lecture and then class time will be focused on hands-on analysis and completing problem sets.

You'll have problem sets to complete after each class, which should take ~60 minutes each. There will also be final projects, which you can do solo or in groups.

The class ends on December 1.

We will be using Posit Cloud for the course and you'll need to bring a laptop to class — it doesn't need to be particularly powerful, all computing will be done in the cloud through a browser. If you don't have a personal laptop, please let us know ASAP.

Please go ahead and log in to Posit Cloud (cloud icon at the top left of the course webpage, under the logo) with your cuanschutz.edu credentials and let me know if you have issues getting in.

Best
