{
  "hash": "6ed86c25a8279850435df30d0029c71d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Stats Bootcamp - class 13\"\nsubtitle: \"Hypothesis testing\"\nauthor: \"{{< var instructor.block.bootcamp-stats >}}\"\neditor: visual\n---\n\n\n\n## Prepare mouse biochem data {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# we are reading the data directly from the internet\nbiochem <- read_tsv(\n  \"http://mtweb.cs.ucl.ac.uk/HSMICE/PHENOTYPES/Biochemistry.txt\",\n  show_col_types = FALSE\n) |>\n  janitor::clean_names()\n\n# simplify names a bit more\ncolnames(biochem) <- gsub(\n  pattern = \"biochem_\",\n  replacement = \"\",\n  colnames(biochem)\n)\n\n# we are going to simplify this a bit and only keep some columns\nkeep <- colnames(biochem)[c(1, 6, 9, 14, 15, 24:28)]\nbiochem <- biochem[, keep]\n\n# get weights for each individual mouse\n# careful: did not come with column names\nweight <- read_tsv(\n  \"http://mtweb.cs.ucl.ac.uk/HSMICE/PHENOTYPES/weight\",\n  col_names = F,\n  show_col_types = FALSE\n)\n\n# add column names\ncolnames(weight) <- c(\"subject_name\", \"weight\")\n\n# add weight to biochem table and get rid of NAs\n# rename gender to sex\nb <- inner_join(biochem, weight, by = \"subject_name\") |>\n  na.omit() |>\n  rename(sex = gender)\n```\n:::\n\n\n## Learning objectives\n\n-   **Formulate** and **Execute** null hypothesis testing\n-   **Identify** and **Perform** the proper statistical test for data type/comparison\n-   **Calculate** and **Interpret** p-values\n\n## Parametric vs Nonparametric tests\n\n**Parametric tests** are suitable for normally distributed data.\n\n**Nonparametric tests** are suitable for any continuous data. Though these tests have their own sets of assumption, you can think of Nonparametric tests as the **ranked versions of the corresponding parametric tests**.\n\n[More on choosing Parametric vs Non-Parametric](https://statisticsbyjim.com/hypothesis-testing/nonparametric-parametric-tests/)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tynablfmhe\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tynablfmhe table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tynablfmhe thead, #tynablfmhe tbody, #tynablfmhe tfoot, #tynablfmhe tr, #tynablfmhe td, #tynablfmhe th {\n  border-style: none;\n}\n\n#tynablfmhe p {\n  margin: 0;\n  padding: 0;\n}\n\n#tynablfmhe .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tynablfmhe .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tynablfmhe .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tynablfmhe .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tynablfmhe .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tynablfmhe .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tynablfmhe .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tynablfmhe .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tynablfmhe .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tynablfmhe .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tynablfmhe .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tynablfmhe .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tynablfmhe .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tynablfmhe .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tynablfmhe .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tynablfmhe .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tynablfmhe .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tynablfmhe .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tynablfmhe .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tynablfmhe .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tynablfmhe .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tynablfmhe .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tynablfmhe .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tynablfmhe .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tynablfmhe .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tynablfmhe .gt_left {\n  text-align: left;\n}\n\n#tynablfmhe .gt_center {\n  text-align: center;\n}\n\n#tynablfmhe .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tynablfmhe .gt_font_normal {\n  font-weight: normal;\n}\n\n#tynablfmhe .gt_font_bold {\n  font-weight: bold;\n}\n\n#tynablfmhe .gt_font_italic {\n  font-style: italic;\n}\n\n#tynablfmhe .gt_super {\n  font-size: 65%;\n}\n\n#tynablfmhe .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tynablfmhe .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tynablfmhe .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tynablfmhe .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tynablfmhe .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tynablfmhe .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tynablfmhe .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tynablfmhe .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tynablfmhe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Info\">Info</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parametric\">Parametric</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Nonparametric\">Nonparametric</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Info\" class=\"gt_row gt_left\">better descriptor</td>\n<td headers=\"Parametric\" class=\"gt_row gt_left\">mean</td>\n<td headers=\"Nonparametric\" class=\"gt_row gt_left\">median  </td></tr>\n    <tr><td headers=\"Info\" class=\"gt_row gt_left\"># of samples (N)</td>\n<td headers=\"Parametric\" class=\"gt_row gt_left\">many</td>\n<td headers=\"Nonparametric\" class=\"gt_row gt_left\">few</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Random variables\n\n**Response Variable** ( **y** - aka dependent or outcome variable): this variable is predicted or its variation is explained by the explanatory variable. In an experiment, this is the outcome that is measured following manipulation of the explanatory variable.\n\n**Explanatory Variable** ( **x** - aka independent or predictor variable): explains variations in the response variable. In an experiment, it is manipulated by the researcher.\n\n## Appropriate statistical test cheatsheet\n\n![](/img/stats_table.png)\n\n## Relationship between 2 or more quantitative variables?\n\n**Correlation:** summarize the direction and strength of the relationships between 2 or more variables. \n\n**Regression:** build model/formula to predict a response, $y$, from one or more explanatory variable $x$.\n\n## Association between two continuous variables (x and y) {.smaller}\n\n$y$ is independent of $x$\n\n$y$ is continuous\n\n$x$ is continuous\n\n**Parametric: Pearson correlation**\n\n`cor_test(x, y, method=\"Pearson\")`\n\n**Nonparametric: Spearman correlation (ranked values)**\n\n`cor_test(x, y, method=\"Spearman\")`\n\n1.  Declare null hypothesis $\\mathcal{H}_0$\n2.  Calculate test-statistic, exact p-value\n\n## Correlation vs Regression {.smaller}\n\n|   | Correlation | Regression |\n|------------------|-------------------------|-----------------------------|\n| **Description** | Association between 2 or more variables | How an response variable is numerically related to explanatory variable(s) |\n| **Usage** | To represent linear relationship between two variables | To fit a best line and estimate one variable on the basis of another variable |\n| **Response vs Explanatory variables** | Doesn't matter | must define (i.e. order of relationship matters) |\n| **Interpretation** | Correlation coefficient indicates direction and extent to which two variables move together | Regression indicates the impact of a unit change in the explanatory variable (x) on the response variable (y) |\n| **Goal** | To find a numerical value expressing the relationship between variables | To estimate values of response variable on the basis of the values of explanatory variable(s) |\n\n## Null hypothesis testing\n\n1.  Examine and specify the variable(s)\n2.  Declare null hypothesis $\\mathcal{H}_0$\n3.  Calculate test-statistic, exact p-value\n\n. . .\n\nWe will not stick to this super closely for correlation, but will for regression.\n\n## Pearson correlation {.smaller}\n\nIt was developed by [Karl Pearson](https://en.wikipedia.org/wiki/Karl_Pearson \"Karl Pearson\") from a related idea introduced by [Francis Galton](https://en.wikipedia.org/wiki/Francis_Galton \"Francis Galton\") in the 1880s, and for which the mathematical formula was derived and published by [Auguste Bravais](https://en.wikipedia.org/wiki/Auguste_Bravais \"Auguste Bravais\") in 1844.^[\\[a\\]](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#cite_note-6)[\\[6\\]](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#cite_note-7)[\\[7\\]](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#cite_note-8)[\\[8\\]](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#cite_note-9)[\\[9\\]](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#cite_note-10)^ The naming of the coefficient is thus an example of [Stigler's Law](https://en.wikipedia.org/wiki/Stigler%27s_Law \"Stigler's Law\") (see list of examples [here](https://en.wikipedia.org/wiki/List_of_examples_of_Stigler%27s_law)).\n\nInterpretation of coefficient:\n\n1 = perfect linear correlation\n\n0 = no correlation\n\n-1 = perfect linear anti-correlation\n\n$Corr(x,y) = \\displaystyle \\frac {\\sum_{i=1}^{n} (x_{i} - \\overline{x})(y_{i} - \\overline{y})}{\\sum_{i=1}^{n} \\sqrt(x_{i} - \\overline{x})^2 \\sqrt(y_{i} - \\overline{y})^2}$\n\n$x_{i}$ = the \"i-th\" observation of the variable $x$\n\n$\\overline{x}$ = mean of all observations of $x$\n\n$y_{i}$ = the \"i-th\" observation of the variable $y$\n\n$\\overline{y}$ = mean of all observations of $y$\n\n## Association between mouse $weight$ and $tot\\_cholesterol$ {.smaller}\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nggscatter(data = b, y = \"weight\", x = \"tot_cholesterol\")\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\nwe previously established these are normal enough \\> $\\mathcal{H}_0$ is no (linear) relationship between $tot\\_cholesterol$ and $weight$\n\n------------------------------------------------------------------------\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nb |>\n  cor_test(weight, tot_cholesterol, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n  var1   var2      cor statistic        p conf.low conf.high\n  <chr>  <chr>   <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 weight tot_ch…  0.35      16.0 8.92e-54    0.313     0.394\n# ℹ 1 more variable: method <chr>\n```\n\n\n:::\n:::\n\n\nP value well below 0.05\n\n> $\\mathcal{H}_0$ is no relationship between $tot\\_cholesterol$ and $weight$ **NOT WELL SUPPORTED**\n\nSo there is a (linear) relationship between $tot\\_cholesterol$ and $weight$\n\n## Visualize Pearson correlation {.smaller}\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nggscatter(\n  data = b,\n  y = \"weight\",\n  x = \"tot_cholesterol\"\n) +\n  stat_cor(\n    method = \"pearson\",\n    label.x = 1,\n    label.y = 30\n  )\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## Manual calculation of Pearson correlation {.smaller}\n\n$Corr(x,y) = \\displaystyle \\frac {\\sum_{i=1}^{n} (x_{i} - \\overline{x})(y_{i} - \\overline{y})}{\\sum_{i=1}^{n} \\sqrt(x_{i} - \\overline{x})^2 \\sqrt(y_{i} - \\overline{y})^2}$\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\n# mean total cholesterol\nm_chol <- mean(b$tot_cholesterol)\n\n# average weight\nm_weight <- mean(b$weight)\n\n# difference from mean total cholesterol\ndiff_chol <- b$tot_cholesterol - m_chol\n\n# difference from mean total cholesterol\ndiff_weight <- b$weight - m_weight\n\n# follow formula above\nmanual_pearson <- sum(diff_chol * diff_weight) /\n  (sqrt(sum(diff_chol^2)) * sqrt(sum(diff_weight^2)))\n\nmanual_pearson\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3540731\n```\n\n\n:::\n:::\n\n\n## Spearman Correlation (nonparametric) {.smaller}\n\n[Spearman's rank correlation coefficient](https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient)or Spearman's ρ, named after Charles Spearman is a **nonparametric** measure of **rank** correlation (statistical dependence between the rankings of two variables). It assesses how well the relationship between two variables can be described using a monotonic function.\n\nMore info [here](https://towardsdatascience.com/clearly-explained-pearson-v-s-spearman-correlation-coefficient-ada2f473b8#:~:text=The%20fundamental%20difference%20between%20the,with%20monotonic%20relationships%20as%20well.).\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nb |>\n  cor_test(weight, tot_cholesterol, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  var1   var2              cor  statistic        p method  \n  <chr>  <chr>           <dbl>      <dbl>    <dbl> <chr>   \n1 weight tot_cholesterol  0.36 603954134. 1.54e-55 Spearman\n```\n\n\n:::\n:::\n\n\nP value well below 0.05\n\n> $\\mathcal{H}_0$ is no relationship between $tot\\_cholesterol$ and $weight$ **NOT WELL SUPPORTED**\n\n## Visualize Spearman correlation\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nggscatter(\n  data = b,\n  y = \"weight\",\n  x = \"tot_cholesterol\"\n) +\n  stat_cor(\n    method = \"spearman\",\n    label.x = 1,\n    label.y = 30\n  )\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n## Let's create a hypothetical example {.smaller}\n\ncreate tibble $d$ with variables $x$ and $y$\n\n$x$, 1:50\n\n$y$, which is $x^{10}$\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nd <- tibble(\n  x = seq(1:50),\n  y = x^10\n)\n```\n:::\n\n\n. . .\n\nscatter plot\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nggscatter(data = d, x = \"x\", y = \"y\")\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\nPearson\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nd |>\n  cor_test(x, y, method = \"pearson\") |>\n  select(cor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n    cor\n  <dbl>\n1  0.67\n```\n\n\n:::\n:::\n\n\n. . .\n\nSpearman\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nd |>\n  cor_test(x, y, method = \"spearman\") |>\n  select(cor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n    cor\n  <dbl>\n1     1\n```\n\n\n:::\n:::\n\n\n## Additional examples with correlation {.smaller}\n\ncompare 1 variable to all other quantitative variables\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nb |>\n  cor_test(weight, method = \"spearman\") |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"bgpuhcxqqs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bgpuhcxqqs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bgpuhcxqqs thead, #bgpuhcxqqs tbody, #bgpuhcxqqs tfoot, #bgpuhcxqqs tr, #bgpuhcxqqs td, #bgpuhcxqqs th {\n  border-style: none;\n}\n\n#bgpuhcxqqs p {\n  margin: 0;\n  padding: 0;\n}\n\n#bgpuhcxqqs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bgpuhcxqqs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bgpuhcxqqs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bgpuhcxqqs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bgpuhcxqqs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bgpuhcxqqs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bgpuhcxqqs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bgpuhcxqqs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bgpuhcxqqs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bgpuhcxqqs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bgpuhcxqqs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bgpuhcxqqs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bgpuhcxqqs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bgpuhcxqqs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bgpuhcxqqs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bgpuhcxqqs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bgpuhcxqqs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bgpuhcxqqs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bgpuhcxqqs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bgpuhcxqqs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bgpuhcxqqs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bgpuhcxqqs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bgpuhcxqqs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bgpuhcxqqs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bgpuhcxqqs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bgpuhcxqqs .gt_left {\n  text-align: left;\n}\n\n#bgpuhcxqqs .gt_center {\n  text-align: center;\n}\n\n#bgpuhcxqqs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bgpuhcxqqs .gt_font_normal {\n  font-weight: normal;\n}\n\n#bgpuhcxqqs .gt_font_bold {\n  font-weight: bold;\n}\n\n#bgpuhcxqqs .gt_font_italic {\n  font-style: italic;\n}\n\n#bgpuhcxqqs .gt_super {\n  font-size: 65%;\n}\n\n#bgpuhcxqqs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bgpuhcxqqs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bgpuhcxqqs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bgpuhcxqqs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bgpuhcxqqs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bgpuhcxqqs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bgpuhcxqqs .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#bgpuhcxqqs .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#bgpuhcxqqs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"var1\">var1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"var2\">var2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cor\">cor</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">calcium</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">0.110</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">842963811</td>\n<td headers=\"p\" class=\"gt_row gt_right\">7.02e-06</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Spearman</td></tr>\n    <tr><td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">glucose</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">0.120</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">826420593</td>\n<td headers=\"p\" class=\"gt_row gt_right\">1.60e-07</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Spearman</td></tr>\n    <tr><td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">sodium</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">0.190</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">761019970</td>\n<td headers=\"p\" class=\"gt_row gt_right\">1.99e-16</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Spearman</td></tr>\n    <tr><td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">tot_cholesterol</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">0.360</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">603954134</td>\n<td headers=\"p\" class=\"gt_row gt_right\">1.54e-55</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Spearman</td></tr>\n    <tr><td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">age</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">0.150</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">798746789</td>\n<td headers=\"p\" class=\"gt_row gt_right\">8.23e-11</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Spearman</td></tr>\n    <tr><td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">cage_density</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">-0.100</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">1039415036</td>\n<td headers=\"p\" class=\"gt_row gt_right\">1.58e-05</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Spearman</td></tr>\n    <tr><td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">litter</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">-0.035</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">976251231</td>\n<td headers=\"p\" class=\"gt_row gt_right\">1.38e-01</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Spearman</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nrelationship between $weight$ and $tot\\_cholesterol$ by $sex$\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nb |>\n  group_by(sex) |>\n  cor_test(weight, tot_cholesterol, method = \"pearson\") |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gztlilfiwg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gztlilfiwg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gztlilfiwg thead, #gztlilfiwg tbody, #gztlilfiwg tfoot, #gztlilfiwg tr, #gztlilfiwg td, #gztlilfiwg th {\n  border-style: none;\n}\n\n#gztlilfiwg p {\n  margin: 0;\n  padding: 0;\n}\n\n#gztlilfiwg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gztlilfiwg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gztlilfiwg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gztlilfiwg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gztlilfiwg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gztlilfiwg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gztlilfiwg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gztlilfiwg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gztlilfiwg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gztlilfiwg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gztlilfiwg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gztlilfiwg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gztlilfiwg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gztlilfiwg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gztlilfiwg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gztlilfiwg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gztlilfiwg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gztlilfiwg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gztlilfiwg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gztlilfiwg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gztlilfiwg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gztlilfiwg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gztlilfiwg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gztlilfiwg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gztlilfiwg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gztlilfiwg .gt_left {\n  text-align: left;\n}\n\n#gztlilfiwg .gt_center {\n  text-align: center;\n}\n\n#gztlilfiwg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gztlilfiwg .gt_font_normal {\n  font-weight: normal;\n}\n\n#gztlilfiwg .gt_font_bold {\n  font-weight: bold;\n}\n\n#gztlilfiwg .gt_font_italic {\n  font-style: italic;\n}\n\n#gztlilfiwg .gt_super {\n  font-size: 65%;\n}\n\n#gztlilfiwg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gztlilfiwg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gztlilfiwg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gztlilfiwg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gztlilfiwg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gztlilfiwg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gztlilfiwg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gztlilfiwg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gztlilfiwg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sex\">sex</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"var1\">var1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"var2\">var2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cor\">cor</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"sex\" class=\"gt_row gt_left\">F</td>\n<td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">tot_cholesterol</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">0.10</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.063798</td>\n<td headers=\"p\" class=\"gt_row gt_right\">0.002250</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.03678781</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.1667760</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Pearson</td></tr>\n    <tr><td headers=\"sex\" class=\"gt_row gt_left\">M</td>\n<td headers=\"var1\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"var2\" class=\"gt_row gt_left\">tot_cholesterol</td>\n<td headers=\"cor\" class=\"gt_row gt_right\">0.12</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.558249</td>\n<td headers=\"p\" class=\"gt_row gt_right\">0.000393</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.05323591</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.1827541</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Pearson</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Appropriate statistical test cheatsheet\n\n![](/img/stats_table.png)\n\n## Regression\n\nWe are going to change our frame work to learn about regression. The nice thing is that everything we learn for regression is applicable to all the tests we just learned.\n\n## The simplicity underlying common tests\n\nMost of the common statistical models (t-test, correlation, ANOVA; etc.) are special cases of linear models or a very close approximation. This simplicity means that there is less to learn. It all comes down to:\n\n> $y = a \\cdot x + b$\n\nThis needless complexity multiplies when students try to rote learn the parametric assumptions underlying each test separately rather than deducing them from the linear model.\n\n## Equation for a line {.smaller}\n\nRemember:\\\n$y = a \\cdot x + b$\\\nOR\\\n$y = b + a \\cdot x$\n\n$a$ is the **SLOPE** (2) $b$ is the **y-intercept** (1)\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nd <- tibble(\n  x = c(-1, 3),\n  y = c(-1, 6)\n)\n\nggplot(data = d, aes(x = x, y = y)) +\n  geom_blank() +\n  geom_abline(\n    intercept = 1,\n    slope = 2,\n    col = \"red\"\n  ) +\n  theme_linedraw()\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-16-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=960}\n:::\n:::\n\n\n## Stats equation for a line {.smaller}\n\nModel:\n\n$y$ equals the intercept ($\\beta_0$) pluss a slope ($\\beta_1$) times $x$.\n\n$y = \\beta_0 + \\beta_1 x \\qquad \\qquad \\mathcal{H}_0: \\beta_1 = 0$\n\n... which is the same as $y = b + a \\cdot x$.\n\nThe short hand for this in R: `y ~ 1 + x`\n\nR interprets this as:\n\n`y = 1*number + x*othernumber`\n\nThe task of t-tests, lm, etc., is simply to find the numbers that best predict $y$.\n\n## Stats equation for a line {.smaller}\n\nAll you need is an intercept ($\\beta_0$) and a slope ($\\beta_1$) to get a line:\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nggplot(data = d, aes(x = x, y = y)) +\n  geom_blank() +\n  geom_abline(\n    intercept = 1,\n    slope = 2,\n    col = \"red\"\n  ) +\n  theme_linedraw()\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-17-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=192}\n:::\n:::\n\n\n$\\beta_0$ = 1 (the y-intercept), $\\beta_1$ = 2 (the slope)\n\n$y = \\beta_0 \\cdot 1 + \\beta_1 \\cdot x$\\\n\n$y = 1 \\cdot 1 + 2 \\cdot x$\n\n$y = 1 + 2x$\n\n> Our mission: **FIND THE BEST** $\\beta$ coefficients\n\n## Linear Regression\n\n-   STEP 1: Make a scatter plot visualize the linear relationship between x and y.\n-   STEP 2: Perform the regression\n-   STEP 3: Look at the $R^2$, $F$-value and $p$-value\n-   STEP 4: Visualize fit and errors\n-   STEP 5: Calculate $R^2$, $F$-value and $p$-value ourselves\n\n## STEP 1: Can mouse cholesterol levels explain mouse weight?\n\nPlot $weight$ (y, response variable) and $tot_cholesterol$ (x, explanatory variable)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = b,\n  aes(\n    y = weight,\n    x = tot_cholesterol\n  )\n) +\n  geom_point(size = .5) +\n  scale_color_manual() +\n  theme_linedraw()\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-18-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=960}\n:::\n:::\n\n\n## STEP 2: Do the regression {.smaller}\n\nKeep calm and fit a line! Remember: $y = \\beta_0 \\cdot 1+ \\beta_1 \\cdot x$\n\nlinear model equation: $weight = \\beta_0 \\cdot 1 + \\beta_1 \\cdot tot\\_cholesterol$\n\n> $\\mathcal{H}_0:$ $tot\\_cholesterol$ does NOT explain $weight$ Null Hypothesis: $\\mathcal{H}_0: \\beta_1 = 0$\n\n$weight = \\beta_0 \\cdot 1 + 0 \\cdot tot\\_cholesterol$ $weight = \\beta_0 \\cdot 1$\n\n> $\\mathcal{H}_1:$ Mouse $tot\\_cholesterol$ does explain $weight$\n\n$weight = \\beta_0 \\cdot 1 + \\beta_1 \\cdot tot\\_cholesterol$\n\nThe cool thing here is that we can assess and compare our null and alternative hypothesis by learning and examining the model coefficients (namely the slope). Ultimately, we are comparing a complex model (with cholesterol) to a simple model (without cholesterol).\n\n<https://statisticsbyjim.com/regression/interpret-constant-y-intercept-regression/>\n\n## STEP 4: Look at the $R^2$, $F$-value and $p$-value {.smaller}\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\n# fitting a line\nfit_WvC <- lm(\n  data = b,\n  formula = weight ~ 1 + tot_cholesterol\n)\n\n\n# base R summary of fit\nsummary(fit_WvC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weight ~ 1 + tot_cholesterol, data = b)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.9624 -2.1349 -0.2627  2.0113 10.2927 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      14.5560     0.3635   40.04   <2e-16 ***\ntot_cholesterol   1.8516     0.1159   15.97   <2e-16 ***\n---\nSignif. codes:  \n0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.121 on 1780 degrees of freedom\nMultiple R-squared:  0.1254,\tAdjusted R-squared:  0.1249 \nF-statistic: 255.1 on 1 and 1780 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThat's a lot of info, but how would I access it? Time to meet your new best friend:\n\n[Broom](%22https://cran.r-project.org/web/packages/broom/vignettes/broom.html%22)\n\n## Tidying output {.smaller}\n\ninformation about the model fit\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nglance(fit_WvC) |>\n  gt() |>\n  fmt_number(columns = r.squared:statistic, decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xnxcgumzlw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xnxcgumzlw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xnxcgumzlw thead, #xnxcgumzlw tbody, #xnxcgumzlw tfoot, #xnxcgumzlw tr, #xnxcgumzlw td, #xnxcgumzlw th {\n  border-style: none;\n}\n\n#xnxcgumzlw p {\n  margin: 0;\n  padding: 0;\n}\n\n#xnxcgumzlw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xnxcgumzlw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xnxcgumzlw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xnxcgumzlw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xnxcgumzlw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xnxcgumzlw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xnxcgumzlw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xnxcgumzlw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xnxcgumzlw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xnxcgumzlw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xnxcgumzlw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xnxcgumzlw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xnxcgumzlw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xnxcgumzlw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xnxcgumzlw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnxcgumzlw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xnxcgumzlw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xnxcgumzlw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xnxcgumzlw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnxcgumzlw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xnxcgumzlw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnxcgumzlw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xnxcgumzlw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnxcgumzlw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xnxcgumzlw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnxcgumzlw .gt_left {\n  text-align: left;\n}\n\n#xnxcgumzlw .gt_center {\n  text-align: center;\n}\n\n#xnxcgumzlw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xnxcgumzlw .gt_font_normal {\n  font-weight: normal;\n}\n\n#xnxcgumzlw .gt_font_bold {\n  font-weight: bold;\n}\n\n#xnxcgumzlw .gt_font_italic {\n  font-style: italic;\n}\n\n#xnxcgumzlw .gt_super {\n  font-size: 65%;\n}\n\n#xnxcgumzlw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xnxcgumzlw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xnxcgumzlw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xnxcgumzlw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xnxcgumzlw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xnxcgumzlw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xnxcgumzlw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xnxcgumzlw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xnxcgumzlw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"r.squared\">r.squared</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"adj.r.squared\">adj.r.squared</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sigma\">sigma</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"logLik\">logLik</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"AIC\">AIC</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"BIC\">BIC</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"deviance\">deviance</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"nobs\">nobs</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"r.squared\" class=\"gt_row gt_right\">0.125</td>\n<td headers=\"adj.r.squared\" class=\"gt_row gt_right\">0.125</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">3.121</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">255.141</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">8.924155e-54</td>\n<td headers=\"df\" class=\"gt_row gt_right\">1</td>\n<td headers=\"logLik\" class=\"gt_row gt_right\">-4555.615</td>\n<td headers=\"AIC\" class=\"gt_row gt_right\">9117.229</td>\n<td headers=\"BIC\" class=\"gt_row gt_right\">9133.686</td>\n<td headers=\"deviance\" class=\"gt_row gt_right\">17335.95</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">1780</td>\n<td headers=\"nobs\" class=\"gt_row gt_right\">1782</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\ninformation about the intercept and coefficients\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\ntidy(fit_WvC) |>\n  gt() |>\n  fmt_number(columns = estimate:statistic, decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uqgtjgxpqc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uqgtjgxpqc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uqgtjgxpqc thead, #uqgtjgxpqc tbody, #uqgtjgxpqc tfoot, #uqgtjgxpqc tr, #uqgtjgxpqc td, #uqgtjgxpqc th {\n  border-style: none;\n}\n\n#uqgtjgxpqc p {\n  margin: 0;\n  padding: 0;\n}\n\n#uqgtjgxpqc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uqgtjgxpqc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uqgtjgxpqc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uqgtjgxpqc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uqgtjgxpqc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uqgtjgxpqc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uqgtjgxpqc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uqgtjgxpqc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uqgtjgxpqc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uqgtjgxpqc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uqgtjgxpqc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uqgtjgxpqc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uqgtjgxpqc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uqgtjgxpqc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uqgtjgxpqc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqgtjgxpqc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uqgtjgxpqc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uqgtjgxpqc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uqgtjgxpqc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqgtjgxpqc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uqgtjgxpqc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqgtjgxpqc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uqgtjgxpqc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqgtjgxpqc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uqgtjgxpqc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uqgtjgxpqc .gt_left {\n  text-align: left;\n}\n\n#uqgtjgxpqc .gt_center {\n  text-align: center;\n}\n\n#uqgtjgxpqc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uqgtjgxpqc .gt_font_normal {\n  font-weight: normal;\n}\n\n#uqgtjgxpqc .gt_font_bold {\n  font-weight: bold;\n}\n\n#uqgtjgxpqc .gt_font_italic {\n  font-style: italic;\n}\n\n#uqgtjgxpqc .gt_super {\n  font-size: 65%;\n}\n\n#uqgtjgxpqc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uqgtjgxpqc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uqgtjgxpqc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uqgtjgxpqc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uqgtjgxpqc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uqgtjgxpqc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uqgtjgxpqc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uqgtjgxpqc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uqgtjgxpqc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">14.556</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.363</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">40.044</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.482991e-250</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">tot_cholesterol</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.852</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.116</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">15.973</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">8.924155e-54</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nsave the intercept and slope into variable to use later\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nchol_intercept <- tidy(fit_WvC)[1, 2]\n\nchol_slope <- tidy(fit_WvC)[2, 2]\n```\n:::\n\n\n------------------------------------------------------------------------\n\n> for every 1 unit increase in cholesterol there is a 1.85 unit increase weight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = b,\n  aes(\n    y = weight,\n    x = tot_cholesterol\n  )\n) +\n  geom_smooth(method = \"lm\") +\n  geom_point(size = .5) +\n  scale_color_manual() +\n  theme_linedraw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-22-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=960}\n:::\n:::\n\n\n## Collecting residuals and other information {.smaller}\n\nadd residuals and other information\n\n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\nb_WvC <- augment(fit_WvC, data = b)\n\nb_WvC\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,782 × 17\n   subject_name calcium glucose sodium tot_cholesterol\n   <chr>          <dbl>   <dbl>  <dbl>           <dbl>\n 1 A048005080      1.97   12.2     123            3.01\n 2 A048005112      2.11   11.0     133            2.46\n 3 A048006555      1.71    5.97    119            3.57\n 4 A048007096      2.49   10.6     148            2.61\n 5 A048010273      2.14   11.9     131            2.04\n 6 A048010371      2.16   10.6     134            2.86\n 7 A048011287      2.29    9.62    146            3.22\n 8 A048011554      1.69    9.82    117            3.47\n 9 A048012562      1.84   11.0     121            3.35\n10 A048013559      2.31    4.96    144            2.29\n# ℹ 1,772 more rows\n# ℹ 12 more variables: family <chr>, sex <chr>, age <dbl>,\n#   cage_density <dbl>, litter <dbl>, weight <dbl>,\n#   .fitted <dbl>, .resid <dbl>, .hat <dbl>, .sigma <dbl>,\n#   .cooksd <dbl>, .std.resid <dbl>\n```\n\n\n:::\n:::\n\n\n## What are **Residuals** {.smaller}\n\n**Residuals**, $e$ --- the difference between the observed value of the response variable $y$ and the explanatory value $\\widehat{y}$ is called the residual. Each data point has one residual. Specifically, it is the distance on the y-axis between the observed $y_{i}$ and the fit line.\n\n$e = y_{i} - \\widehat{y}$\n\nResiduals with large absolute values indicate the data point is NOT well explained by the model.\n\n## STEP 5: Visualize fit and errors\n\nVisualize the residuals OR the error around the fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = b_WvC,\n  aes(x = tot_cholesterol, y = weight)\n) +\n  geom_point(size = 1, aes(color = .resid)) +\n  geom_abline(\n    intercept = pull(chol_intercept),\n    slope = pull(chol_slope),\n    col = \"red\"\n  ) +\n  scale_color_gradient2(\n    low = \"blue\",\n    mid = \"black\",\n    high = \"yellow\"\n  ) +\n  geom_segment(\n    aes(\n      xend = tot_cholesterol,\n      yend = .fitted\n    ),\n    alpha = .1\n  ) + # plot line representing residuals\n  theme_linedraw()\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-24-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\nVisualize the total error OR the error around the null. So no cholesterol fit, just the mean of y.\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_weight <- mean(b_WvC$weight)\n\nggplot(\n  data = b_WvC,\n  aes(x = tot_cholesterol, y = weight)\n) +\n  geom_point(size = 1, aes(color = weight - avg_weight)) +\n  geom_abline(\n    intercept = avg_weight,\n    slope = 0,\n    col = \"red\"\n  ) +\n  scale_color_gradient2(\n    low = \"blue\",\n    mid = \"black\",\n    high = \"yellow\"\n  ) +\n  geom_segment(\n    aes(\n      xend = tot_cholesterol,\n      yend = avg_weight\n    ),\n    alpha = 25\n  ) + # plot line representing residuals\n  theme_linedraw()\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-25-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=960}\n:::\n:::\n\n\n## STEP 6: Calculate $R^2$, $F$-value, $p$-value ourselves {.smaller}\n\n## What is $R^2$ {.smaller}\n\n$R^2$ --- the coefficient of determination, which is the proportion of the variance in the response variable that is predictable from the explanatory variable(s).\n\n$R^2 = 1 - \\displaystyle \\frac {SS_{fit}}{SS_{null}}$\n\n$SS_{fit}$ --- sum of squared errors around the least-squares fit\n\n$SS_{fit} = \\sum_{i=1}^{n} (data - line)^2 = \\sum_{i=1}^{n} (y_{i} - (\\beta_0 \\cdot 1+ \\beta_1 \\cdot x)^2$\n\n$SS_{null}$ --- sum of squared errors around the mean of $y$\n\n$SS_{null} = \\sum_{i=1}^{n} (data - mean)^2 = \\sum_{i=1}^{n} (y_{i} - \\overline{y})^2$\n\n## Calculate $R^2$ {.smaller}\n\n$SS_{fit}$ --- sum of squared errors around the least-squares fit\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nss_fit <- sum(b_WvC$.resid^2)\nss_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17335.95\n```\n\n\n:::\n:::\n\n\n$SS_{null}$ --- sum of squared errors around the mean of $y$\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nss_null <- sum(\n  (b_WvC$weight - avg_weight)^2\n)\nss_null\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19820.85\n```\n\n\n:::\n:::\n\n\n$R^2 = 1 - \\displaystyle \\frac {SS_{fit}}{SS_{null}}$\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nrsq <- 1 - ss_fit / ss_null\n\nglance(fit_WvC) |> select(r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  r.squared\n      <dbl>\n1     0.125\n```\n\n\n:::\n:::\n\n\n. . .\n\nBTW this is the same $R$ as from the Pearson correlation, just squared:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb |>\n  cor_test(weight, tot_cholesterol, method = \"pearson\") |>\n  mutate(rsq = cor^2) |>\n  pull(rsq) |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n cor \n0.12 \n```\n\n\n:::\n:::\n\n\n## Interpret $R^2$\n\nThere is a 13% reduction in the variance when we take mouse $cholesterol$ into account\\\nOR\\\n$cholesterol$ explains 13% of variation in mouse $weight$\n\n## What is the **F-statistic** {.smaller}\n\n**F-statistic** --- based on the ratio of two variances: the explained variance (due to the model) and the unexplained variance (residuals).\n\n$F = \\displaystyle \\frac{SS_{fit}/(p_{fit}-p_{null})} {SS_{null}/(n-p_{fit})}$\n\n$p_{fit}$ --- number of parameters (coefficients) in the fit line\\\n\n$p_{null}$ --- number of parameters (coefficients) in the mean line\\\n\n$n$ --- number of data points\n\n## Calculate the **F-statistic** {.smaller}\n\n$F = \\displaystyle \\frac{SS_{null} - SS_{fit}/(p_{fit}-p_{null})} {SS_{fit}/(n-p_{fit})}$\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\npfit <- 2\npnull <- 1\nn <- nrow(b_WvC)\n\nf <- ((ss_null - ss_fit) / (pfit - pnull)) /\n  (ss_fit / (n - pfit))\n\n\nf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 255.1411\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(fit_WvC) |> select(statistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  statistic\n      <dbl>\n1      255.\n```\n\n\n:::\n:::\n\n\n## P-values {.smaller}\n\nYou don't really need to know what the $F-statistic$ is unless you want to calculate the p-value. In this case we need to generate a null distribution of $F-statistic$ values to compare to our observed $F-statistic$.\n\nTherefore, we will randomize the $tot_cholesterol$ and $weight$ and then calculate the $F-statistic$.\n\n![](https://media.giphy.com/media/3o7TKDedZiHXRJNveU/giphy.gif){width=\"10%\"}\n\n</br>\n\nWe will do this many many times to generate a null distribution of $F-statistic$s.\\\n</br>\n\n![](https://media.giphy.com/media/3o7TKDedZiHXRJNveU/giphy.gif){width=\"5%\"} ![](https://media.giphy.com/media/3o7TKDedZiHXRJNveU/giphy.gif){width=\"5%\"}\\\n![](https://media.giphy.com/media/3o7TKDedZiHXRJNveU/giphy.gif){width=\"5%\"} ![](https://media.giphy.com/media/3o7TKDedZiHXRJNveU/giphy.gif){width=\"5%\"} </br>\n\nThe p-value will be the probability of obtaining an $F-statistic$ in the null distribution at least as extreme as our observed $F-statistic$.\n\n## Let's get started\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\n# set up an empty tibble to hold our null distribution\nfake_biochem <- tribble()\n\n# we will perform 100 permutations\nmyPerms <- 100\n\nfor (i in 1:myPerms) {\n  tmp <- bind_cols(\n    b_WvC[sample(nrow(b_WvC)), \"weight\"],\n    b_WvC[sample(nrow(b_WvC)), \"tot_cholesterol\"],\n    \"perm\" = factor(rep(i, nrow(b_WvC)))\n  )\n\n  fake_biochem <- bind_rows(fake_biochem, tmp)\n  rm(tmp)\n}\n\n\n# let's look at permutations 1 and 2\nggplot(\n  fake_biochem |> filter(perm %in% c(1:2)),\n  aes(x = weight, y = tot_cholesterol, color = perm)\n) +\n  geom_point(size = .1) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-31-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=960}\n:::\n:::\n\n\n## Run 100 linear models!\n\nNow we will calculate and extract linear model results for each permutation individually using nest, mutate, and map functions\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nfake_biochem_lms <- fake_biochem |>\n  nest(data = -perm) |>\n  mutate(\n    fit = map(data, ~ lm(weight ~ tot_cholesterol, data = .x)),\n    glanced = map(fit, glance)\n  ) |>\n  unnest(glanced)\n```\n:::\n\n\n## Visualize the null {.smaller}\n\nLet's take a look at the null distribution of F-statistics from the randomized values\n\n\n::: {.cell output-location='column-fragment'}\n\n```{.r .cell-code}\nggplot(\n  fake_biochem_lms,\n  aes(x = statistic)\n) +\n  geom_density(color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-33-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\nremember that the $F-statistic$ we observed was \\~255!\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nggplot(fake_biochem_lms, aes(x = statistic)) +\n  xlim(0, f * 1.1) +\n  geom_density(color = \"red\") +\n  geom_vline(xintercept = f, color = \"blue\") +\n  #  scale_x_log10() +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](slides-13_files/figure-revealjs/unnamed-chunk-34-1.png){fig-alt='Description of the plot - PLEASE FILL IN' width=960}\n:::\n:::\n\n\nIn our 100 randoized simulations, we never see an F-statistic as extreme as the one we observed in the actual data. Therefore:\n\n> P \\< 0.01 or 1/100\n\nReminder, our calculate P value was:\n\n\n\n## How to find the best (least squares) fit?\n\n1.  Rotate the line of fit\\\n2.  Find the fit that minimizes the Sum of Squared Residuals or $SS_{fit}$\\\n3.  This is the derivative (slope of tangent at best point = 0) of the function describing the $SS_{fit}$ and the next rotation is 0.\n\n## References\n\n[Differences between correlation and regression](https://www.graphpad.com/support/faq/what-is-the-difference-between-correlation-and-linear-regression/)\n\n[also more differences between correlation and regression](https://keydifferences.com/difference-between-correlation-and-regression.html).\n\n[Common statistical tests are linear models](https://lindeloev.github.io/tests-as-linear/) from Jonas Lindeløv\\\n\n[Statquest](https://www.youtube.com/channel/UCtYLUTtgS3k1Fg4y5tAhLbw)\n\n[Stats gobbledygook](https://www.rapidtables.com/math/symbols/Statistical_Symbols.html)\n\n[Linear Regression Assumptions and Diagnostics in R: Essentials](http://www.sthda.com/english/articles/39-regression-model-diagnostics/161-linear-regression-assumptions-and-diagnostics-in-r-essentials/)\\\n\n[PRINCIPLES OF STATISTICS](https://www.graphpad.com/guides/prism/latest/statistics/stat_---_principles_of_statistics_-.htm) from GraphPad/SAS.\n\n[Statquest: how to go from F-statistic to p-value](https://www.youtube.com/watch?v=nk2CQITm_eo)\n\n[StatQuest: Fitting a line to data, aka least squares, aka linear regression.](https://youtu.be/PaFPbb66DxQ)\n\n[StatQuest: Gradient Descent, Step-by-Step](https://youtu.be/sDv4f4s2SB8)\n",
    "supporting": [
      "slides-13_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}