# Python {#bootcamp-python}

[Python](https://www.python.org/) is an easy to learn language that combines the flexibility of bash along with the conveniences of higher level languages like R. This useful for solving problems for which software does not exist, which is important for students to learn in order to anticipate unmet needs and data from new technologies/assays. Many tools for the analysis of modern datasets are available as python packages, allowing the incorporation of pre-built analysis tools within custom, made-from-scratch, code. Furthermore, python's suitability as a scripting language makes it a natural fit for APIs of other common analysis tools.  For example, image analysis pipelines can be constructed in [Fiji](https://imagej.net/Jython_Scripting), allowing the batch processing of many files at once.  

__After this section, students will be able to write basic software and scripts that will enable them to derive meaning from the large datasets typical of modern biology.__ 
