# Course Information {#syllabus-policies}

## Policies 

**Attendance Policy** You are allowed one absence from paper discussion class without penalty. Additional absence from class will result in a full letter grade reduction, unless each absence is made up by writing a critical review of each paper missed. Attendance at mini-proposal discussions and final major proposal discussions is mandatory. Participation is evaluated objectively (number of paper figures presented, number of papers on which the student acted as coordinator, number of questions asked during discussion) and subjectively (quality of contribution to discussion).

**Late Work Policy** Proposals turned in late will be assessed a penalty: a half-letter grade if it is one day late or a full-letter grade for 2-3 days late. Material will not be accepted if greater than 3 days late. Exceptions can be made upon discussion with the course coordinators and considering exceptional circumstances. 

**Extra Credit Policy** No extra credit will be considered. 

**Grades of "Incomplete"** (The current university policy concerning incomplete grades will be followed in this course. Incomplete grades are given only in situations where unexpected emergencies prevent a student from completing the course and the remaining work can be completed the next semester. Your instructors and the Program Directors are the final authorities on whether you qualify for an incomplete. Incomplete work must be finished by the end of the subsequent semester or the “I” will automatically be recorded as an “F” on your transcript. 

**Rewrite/Resubmit Policy** The critical paper reviews required in lieu of class attendance may be returned to the student for a re-write if the course directors and/or block faculty deem them insufficient. 

**Group Work Policy** Students are encouraged to work together to prepare for paper discussions, although this is not necessary. Students are encouraged to share drafts of their mini- and full proposals with other students and faculty prior to submission, although it is expected that if multiple students choose to prepare proposals relating to the same subject or hypothesis, these students should recognize the potential for inappropriate sharing of ideas, and should avoid sharing their work with other such students. Feedback given between students should be general in terms of the science, or specific in terms of writing style/grammar/spelling, but not specific in terms of explicit changes in experimental approaches or hypotheses.

## Technology and Media

**Email** Email and Canvas are expected to be the primary method of communication between faculty and students outside of class, but students are also encouraged to speak directly with faculty after having arranged a time beforehand. Canvas will be the primary method by which course information is disseminated to the students, and the method by which students are expected to submit their assignments.(

**Laptop and Mobile Device Usage** Laptops and tablets are permitted and encouraged in class to facilitate additional searches of the literature during the session.

## Student Expectations

**Civility** Our commitment is to create a climate for learning characterized by respect for each other and the contributions each person makes to class. We ask that you make a similar commitment. Criticism of work written by another student is expected to be constructive and articulated in a manner that is considerate of the effort that all students are expected to put into their work. As class participation during discussions is a crucial component of the grading for this course, students are encouraged to allow others the opportunity to participate, and avoid dominating the discussion. Faculty may intervene if this becomes a problem.

**Professionalism** Mobile devices must be silenced during all classroom meetings. Those not heeding this rule will be asked to leave the classroom/lab immediately so as to not disrupt the learning environment. 

**Electronic Cigarettes (e-cigarettes)** The use of e-cigarettes during all classroom activity is prohibited. Any student who does not comply with this rule will be asked to leave the classroom immediately so as to not disrupt the learning environment. The Anschutz Medical Campus is a tobacco-free campus.

**Late Arrivals** Late arrivals at class disrupt the learning environment. If late arrivals by a student becomes a pattern of behavior, course directors will intervene and may deduct grade points.

**Religious Observances** The course directors request that students inform us as early as possible of conflicts between the normal class schedule and major religious observances, and/or if they intend to miss class to observe a holy day of their religious faith. We will be as accommodating as possible.

## University Policies

**Disability Access** Offer specifics about the university’s policy on disability access. Example:(The University of Colorado Denver is committed to providing reasonable accommodation and access to programs and services to persons with disabilities. Students with disabilities who want academic accommodations must register with Disability Resources and Services (DRS) in North Classroom 2514, Phone: 303-556-3450, TTY: 303-556- 4766, Fax: 303-556-4771. We will be happy to provide approved accommodations, once you provide us with a copy of DRS’s letter. 

**Academic Honesty(Student Code of Conduct** Students are expected to know, understand, and comply with the ethical standards of the university, including rules against plagiarism, cheating, fabrication and falsification, multiple submissions, misuse of academic materials, and complicity in academic dishonesty. Please see the Academic Honesty Handbook at: http://www.ucdenver.edu/faculty_staff/faculty/center-for-faculty-development/Documents/ academic_honesty.pdf for suggestions on ways to avoid academic dishonesty. 

**Plagiarism** Plagiarism is the use of another person’s ideas or words without acknowledgement. The incorporation of another person’s work into yours requires appropriate identification and acknowledgement. Examples of plagiarism when the source is not noted include: word- or-word copying of another person’s ideas or words; the “mosaic” (interspersing your own words here and there while, in essence, copying another’s work); the paraphrase (the rewriting of another’s work, while still using their basic ideas or theories); fabrication (inventing or counterfeiting sources); submission of another’s work as your own; and neglecting quotation marks when including direct quotes, even on material that is otherwise acknowledge. 

**Cheating** Cheating involves the possession, communication, or use of information, materials, notes, study aids, or other devices and rubrics not specifically authorized by the course instructor in any academic exercise, or unauthorized communication with any other person during an academic exercise. Examples of cheating include: copying from another’s work or receiving unauthorized assistance from another; collaborating with another or others without the consent of the instructor; submitting another’s work as one’s own. 

**Fabrication** Fabrication involves inventing or counterfeiting information—creating results not properly obtained through study or laboratory experiment. Falsification involves deliberate alteration or changing of results to suit one’s needs in an experiment or academic exercise. 

**Multiple submissions** Multiple submission involves submitting academic work in a current course when academic credit for the work was previously earned in another course, when such submission is made without the current course instructor’s authorization.

**Misuse of materials** Misuse of academic materials includes: theft/destruction of library or reference materials or computer programs; theft/destruction of another student’s notes or materials; unauthorized possession of another student’s notes or materials; theft/destruction of examinations, papers, or assignments; unauthorized assistance in locating/using sources of information when forbidden or not authorized by the instructor; unauthorized possession, disposition, or use of examinations or answer keys; unauthorized alteration, forgery, fabrication, or falsification of academic records; unauthorized sale or purchase of examinations, papers, or assignments.

**Complicity** Complicity in academic dishonesty involves knowingly contributing to or cooperating with another’s act(s) of academic dishonesty. 
