# Evaluation {#syllabus-evaluation}

## Assignments

**Papers** Assigned papers for class discussion are required reading. Students will volunteer or be assigned specific papers for which they will be responsible for presenting an ~10-min Introduction, including a broad overview of the biological question at hand, the specific hypothesis (if applicable), and the methods used by the authors, focusing especially on methods not covered in the Core course or not generally familiar to first-year PhD students. The same student will be responsible for putting together a Powerpoint (or other equivalent software) presentation containing all of the main figures from the paper, broken down (if necessary) into slides in which all data are easily visible when projected on a screen. Certain supplemental figures may be included if the student thinks they might be important, but this is generally not expected. The same student will be expected to obtain a laptop computer (or equivalent hardware) and necessary adapter for connecting to the projector in the classroom; course directors can help with these materials. Further details regarding preparation of the presentation will be provided in the Course Overview on Jan. 23rd. The effectiveness of the coordinator’s Introduction will be considered by the faculty when assigning a grade. The degree of preparation and/or understanding of the paper reflected in the other students’ contributions to the discussion of the paper will be considered by the faculty when assigning a grade. 

**Final Project** Major proposals include a Specific Aims page and a 6-page Research Proposal (generally two specific aims, based on any papers or topics from Blocks #1-3). Further details regarding preparation of the major proposals will be provided in the latter part of the course. Completed proposals will be evaluated by the course faculty and other students and discussed on the final class days of the course in a "Mock Study Section" similar to the mini-proposals.

**Basis for Final Grade**  Your grade will be determined by the cumulative scores determined from the quality and quantity of your contributions to the paper discussions, your performance as a coordinator and presenter of figures, the quality of mini-proposals and the 6-page Major Proposal, and performance in the proposal discussion in Blocks #1-3 and final Study Sections in Block #4. For CSD students, you will only need to write the major proposal for CSD7605 (we can discuss this if you would like to write for MB7800), but you must participate in the final study section discussions in both courses.  The grade for the CSD proposal will be accepted for both courses. You are allowed one absence from paper discussion class without penalty.  Additional absence from class will result in a full letter grade reduction, unless each absence is made up by writing a critical review of each paper missed. Further details regarding preparation of the make-up paper review will be provided in the Course Overview on Jan. 23rd. The grading scale is subjective and based on an arbitrary point system.

## Grade Dissemination 

The course directors will provide a current score update periodically through the course so that students are aware of their standing. Course directors will explicitly notify students if their participation has been below expectations and needs to be improved. The goal is for the students to not have to worry about their grades. Final scores will be sent to the students at the end of the semester. 
