# Course Overview {#syllabus-overview}

Informatics and Statistics for Molecular Biology (MOLB 7950) teaches students to design and analyze experiments commonly used in molecular biology. The course is organized around the Central Dogma (DNA > RNA > Protein) wherein each block presents 2-3 experimental approaches. Each week, a new experiment is introduced with a discussion of appropriate design and statistical considerations. The remaining weeks' classes are devoted to digging into the analysis of a sample data set with hands-on programming.

## Learning Objectives

- Cater to students of many backgrounds (more computational or more biological)
- Be able to formulate questions that are testable with computational techniques
- Understand the limitations of sequencing-based techniques
- Be fluent in statistical considerations for different approaches and design well-controlled experiments that can be analyzed using statistical tests
- Be fluent in command-line programming, scripting (Python) and data analysis / viz (R / R Studio)
- Understand the value of internet-based analysis tools (NCBI BLAST etc)
- Use reproducible software development approaches (Github) and dynamic documents (Rmarkdown)
- Independently conceive of and implement a soup to nuts reanalysis of an existing data set, which are presented to the class.

## Location

Classes are held in the Health Science Libary in Teaching Lab 2.

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d522.3036530801571!2d-104.83760147806905!3d39.746845026837306!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x876c634e33da2401%3A0x17aa3fee1c687c49!2sUniversity+of+Colorado+Strauss+Health+Sciences+Library!5e0!3m2!1sen!2sus!4v1557762606921!5m2!1sen!2sus" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

## Schedule

```{r class_schedule, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gt)

date_start <- "2019-09-02"
date_end <- "2019-12-10"

sched <- tribble(
  ~ date,       ~ block,    ~ topic,    ~ type, ~ due,
  "2019-08-26", "Bootcamp", "Shell",    "lab", "", 
  "2019-08-28", "Bootcamp", "Shell",    "lab", "",
  "2019-08-30", "Bootcamp", "Shell",    "lab", "",
  "2019-09-04", "Bootcamp", "R Studio", "lab", "Quiz 1",
  "2019-09-06", "Bootcamp", "R Studio", "lab", "",
  "2019-09-09", "Bootcamp", "R Studio", "lab", "Quiz 2",
  "2019-09-11", "Bootcamp", "Python",   "lab", "",
  "2019-09-13", "Bootcamp", "Python",   "lab", "",
  "2019-09-16", "Bootcamp", "Python",   "lab", "Quiz 3",
  "2019-09-18", "Bootcamp", "Git / Github", "lab", "",
  "2019-09-20", "Bootcamp", "Review", "lab",  "",
  "2019-09-23", "Block 1: DNA", "ChIP-seq", "lecture",  "Quiz 4",
  "2019-09-25", "Block 1: DNA", "ChIP-seq", "lab", "",
  "2019-09-27", "Block 1: DNA", "ChIP-seq", "lab", "",
  "2019-09-30", "Block 1: DNA", "Motif finding", "lecture",  "Quiz 5",
  "2019-10-02", "Block 1: DNA", "Motif finding",  "lab", "",
  "2019-10-04", "Block 1: DNA", "Motif finding",  "lab", "",
  "2019-10-07", "Block 1: DNA", "Variant calling",  "lecture", "Quiz 6",
  "2019-10-09", "Block 1: DNA", "Variant calling",  "lab", "",
  "2019-10-11", "Block 1: DNA", "Variant calling",  "lab", "",
  "2019-10-16", "Block 2: RNA", "qPCR", "lecture/lab",  "Quiz 7",
  "2019-09-18", "Block 2: RNA", "qPCR", "lab", "",
  "2019-10-21", "Block 2: RNA", "RNA-seq", "lecture",  "Quiz 8",
  "2019-10-23", "Block 2: RNA", "RNA-seq",  "lab", "",
  "2019-10-28", "Block 2: RNA", "RNA-protein interactions",  "lecture", "Quiz 9",
  "2019-10-30", "Block 2: RNA", "RNA-protein interactions",  "lab", "",
  "2019-11-01", "Block 2: RNA", "RNA-protein interactions",  "lab", "",
  "2019-11-04", "Block 3: Protein", "Mass spectrometry", "lecture",  "Quiz 10",
  "2019-11-06", "Block 3: Protein", "Mass spectrometry", "lab", "",
  "2019-11-08", "Block 3: Protein", "Mass spectrometry", "lab", "Quiz 11",
  "2019-11-11", "Block 3: Protein", "Densitometry", "lecture",  "",
  "2019-11-13", "Block 3: Protein", "Densitometry",  "lab", "",
  "2019-11-15", "Block 3: Protein", "Densitometry",  "lab", "Quiz 12",
  "2019-11-18", "Block 3: Protein", "Subcellular localization",  "lecture", "",
  "2019-11-20", "Block 3: Protein", "Subcellular localization",  "lab", "",
  "2019-11-22", "Block 3: Protein", "Subcellular localization",  "lab", "Quiz 13"
)

sched %>%
  group_by(block, topic) %>%
  gt() %>%
  tab_header(
    title = "MOLB 7950 Schedule",
    subtitle = glue::glue("{date_start} to {date_end}")
  ) %>%
  fmt_date(
    columns = vars(date),
    date_style = 3
  )
```

## Important Dates

- [Academic Calendar](http://www.ucdenver.edu/anschutz/studentresources/Registrar/Documents/AcademicCalendars/2019-2020/AcademicCalendar-GradSchool-2019-2020_Fall2019.pdf)
